version: '3'
services:
  app:
    container_name: numismatics_go_app
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile
    env_file:
      - .env
    ports:
      - ${GO_PORT}:${GO_PORT}
    volumes:
      - ./cmd/api:/cmd/api
    depends_on:
      - db
      - migrate
    networks:
      - backend

  db:
    container_name: numismatics_psql_database
    image: postgres:latest
    build:
      dockerfile: Dockerfiles/sql.Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend

  migrate:
    image: migrate/migrate
    container_name: numismatics_migrate_service
    working_dir: /app
    networks:
      - backend
    volumes:
      - ./migrations:/app/migrations
    command: ["-database",  "postgresql://numismatics:numismatics@db/numismatics?sslmode=disable",
              "-path", "./migrations",
              "up"]
    links:
      - db

networks:
  backend: